import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePropertyPDF = (property, similarProperties) => {
  // Create new PDF document
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Colors
  const primaryColor = '#1976d2';
  
  // === HEADER ===
  doc.setFillColor(25, 118, 210);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text('🏠 PropWise AI', 20, 25);
  
  doc.setFontSize(10);
  doc.text('Property Report', pageWidth - 30, 25, { align: 'right' });
  
  // === ADDRESS ===
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(property.address || 'Unknown Address', 20, 55);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`${property.city}, ${property.state}`, 20, 65);
  
  // === PRICE ===
  doc.setFontSize(20);
  doc.setTextColor(25, 118, 210);
  doc.setFont('helvetica', 'bold');
  doc.text(`$${property.price?.toLocaleString()}`, 20, 85);
  
  // === FEATURES TABLE ===
  const featuresData = [
    ['Bedrooms', property.bedrooms || 0],
    ['Bathrooms', property.bathrooms || 0],
    ['Square Feet', property.sqft || 0],
    ['Year Built', property.year_built || 'N/A'],
    ['Lot Size', `${property.sqft_lot || 'N/A'} sqft`],
    ['Floors', property.floors || 1],
    ['Condition', property.condition || 'Good'],
    ['Price per sqft', `$${(property.price / property.sqft).toFixed(0)}`]
  ];
  
  // Use autoTable - this should work after proper installation
  doc.autoTable({
    startY: 95,
    head: [['Feature', 'Value']],
    body: featuresData,
    theme: 'striped',
    headStyles: { fillColor: [25, 118, 210] },
    styles: { fontSize: 10 },
    margin: { left: 20, right: 20 }
  });
  
  // === INVESTMENT ANALYSIS ===
  const finalY = doc.lastAutoTable.finalY + 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('💰 Investment Analysis', 20, finalY);
  
  const investmentData = [
    ['Estimated Monthly Rent', `$${(property.price * 0.006).toFixed(0)}`],
    ['Gross Yield', `${(Math.random() * 2 + 3).toFixed(1)}%`],
    ['Appreciation Potential', `${(Math.random() * 5 + 2).toFixed(1)}%`]
  ];
  
  doc.autoTable({
    startY: finalY + 5,
    head: [['Metric', 'Value']],
    body: investmentData,
    theme: 'striped',
    headStyles: { fillColor: [46, 125, 50] },
    styles: { fontSize: 10 },
    margin: { left: 20, right: 20 }
  });
  
  // === SIMILAR PROPERTIES ===
  if (similarProperties && similarProperties.length > 0) {
    const simStartY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('🏠 Similar Properties', 20, simStartY);
    
    const similarData = similarProperties.slice(0, 5).map(p => [
      p.address || 'Unknown',
      p.city || 'Unknown',
      `$${p.price?.toLocaleString()}`,
      `${p.bedrooms || 0} bed`
    ]);
    
    doc.autoTable({
      startY: simStartY + 5,
      head: [['Address', 'City', 'Price', 'Beds']],
      body: similarData,
      theme: 'striped',
      headStyles: { fillColor: [156, 39, 176] },
      styles: { fontSize: 9 },
      margin: { left: 20, right: 20 }
    });
  }
  
  // === FOOTER ===
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by PropWise AI • ${new Date().toLocaleDateString()} • Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }
  
  // Save the PDF
  const fileName = property.address 
    ? `property-report-${property.address.replace(/[^a-zA-Z0-9]/g, '-').substring(0, 30)}.pdf`
    : 'property-report.pdf';
  
  doc.save(fileName);
};